"use client";
// Root layout component for the Next.js App Router.
// This file defines the top-level layout structure for all pages in the app.
// It includes global styles, font configurations, and navigation links.
// Imports


// Load Google fonts using Next.js font optimization helper.
// `Geist` and `Geist_Mono` are functions provided by next/font/google
// that return font objects including a CSS variable name we can apply
// to our document to use the fonts without additional network requests.
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css"; // global stylesheet for the app
import Link from "next/link";
import { usePathname } from "next/navigation";
// Configure Geist Sans and Geist Mono fonts and expose CSS variable names.
// These variables are applied to the <body> so the fonts are available
// to all components via CSS without manually adding font-face rules.
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Page metadata used by Next.js App Router (title, description, etc.).
const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// RootLayout is the top-level layout for the Next.js App Router.
// It defines the <html> and <body> tags and wraps all pages' content.
// We apply the font CSS variables and any global utility classes here.
export default function RootLayout({ children }) {
  const pathname = usePathname();
  console.log("Current pathname:", pathname);
  return (
    <html lang="en">
      <head>
        {/* Static component  */}
          {/* <link ref='stylesheet' href="../public/style.css"/> */}
      </head>
      <body
        // Apply the font variables and enable antialiasing for cleaner text.
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        {
          pathname !== "/login/teacher" ?
        <ul className="site-header">
          <li>
            <Link href="/" className="nav-link">
              Home
            </Link>
          </li>
          <li>
            <Link href="/about" className="nav-link">
              About
            </Link>
          </li>
          <li>
            <Link href="/login" className="nav-link">
              Login
            </Link>
          </li>
          <li>
            <Link href="/topics" className="nav-link">
              Topics
            </Link>
          </li>
        </ul>
        :null 
}
       {children}
      </body>
    </html>
  );
}
